substitutions:
  language: "pl"
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password
  paper_mono_font: "https://raw.githubusercontent.com/Smuger12/M5PaperMono-HomeAssistant-ESPHome/main/fonts/DejaVuSans.ttf"
  device_name: paper-mono
  frontlight_default_brightness: "20"
  frontlight_timeout_seconds: "10"
  sleep_timeout_seconds: "60"
  screensaver_refresh_minutes: "2"
  status_led_low_battery_threshold: "20"
  components_source: github://Smuger12/M5PaperMono-HomeAssistant-ESPHome@main
  ha_weather_entity: weather.dom
  ha_indoor_temperature_entity: sensor.152832118102940_indoor_temperature
  ha_outdoor_pm25_entity: sensor.openweathermap_pm2_5

controls:
  blocks:
    - name: "Sypialnia"
      entities:
        - entity_id: switch.wlancznik_sonoff
        - entity_id: switch.szafka
        - entity_id: light.podloga
        - entity_id: light.biurko

packages:
  paper_mono:
    url: https://github.com/Smuger12/M5PaperMono-HomeAssistant-ESPHome
    ref: main
    files:
      - packages/paper_mono_base.yaml
    refresh: 0s

api:
  encryption:
    key: !secret paper_mono__encryption_key

captive_portal:

esphome:
  name: papermono
